In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel("online_retail_cleaned.xlsx")

#### Top 10 Customers

In [33]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]
cus = df.groupby('CustomerID')['Revenue'].sum()
cus.sort_values(ascending=False).head(10).reset_index()

   CustomerID    Revenue
0     14646.0  279489.02
1     18102.0  256438.49
2     17450.0  187322.17
3     14911.0  132458.73
4     12415.0  123725.45
5     14156.0  113214.59
6     17511.0   88125.38
7     16684.0   65892.08
8     13694.0   62690.54
9     15311.0   59284.19

#### Every Customer Unique Invoice

In [32]:
cui = df.groupby('CustomerID')['InvoiceNo'].value_counts().reset_index()
cui

       CustomerID InvoiceNo  count
0         12346.0    541431      1
1         12346.0   C541433      1
2         12347.0    573511     47
3         12347.0    537626     31
4         12347.0    542237     29
...           ...       ...    ...
22185     18283.0    560032      1
22186     18283.0    575675      1
22187     18287.0    570715     38
22188     18287.0    554065     29
22189     18287.0    573167      3

[22190 rows x 3 columns]

#### Top 10 Invoice Count Customers

In [31]:
df.groupby('CustomerID')['InvoiceNo'].nunique().sort_values(ascending=False).head(10).reset_index()

   CustomerID  InvoiceNo
0     14911.0        248
1     12748.0        224
2     17841.0        169
3     14606.0        128
4     15311.0        118
5     13089.0        118
6     12971.0         89
7     14527.0         86
8     13408.0         81
9     14646.0         77

#### Every Customer average invoice value

In [38]:
cir = df.groupby(["CustomerID","InvoiceNo"])["Revenue"].sum()
result = cir.groupby("CustomerID").mean().reset_index()
result

      CustomerID      Revenue
0        12346.0     0.000000
1        12347.0   615.714286
2        12348.0   449.310000
3        12349.0  1757.550000
4        12350.0   334.400000
...          ...          ...
4367     18280.0   180.600000
4368     18281.0    80.820000
4369     18282.0    58.866667
4370     18283.0   127.845625
4371     18287.0   612.426667

[4372 rows x 2 columns]

#### Top 10 of customer average invoice value

In [41]:
result.sort_values(by="Revenue", ascending=False).head(10)

      CustomerID      Revenue
10       12357.0  6207.670000
2522     15749.0  5383.975000
282      12688.0  4873.810000
55       12415.0  4758.671154
333      12752.0  4366.780000
4347     18251.0  4314.720000
4233     18102.0  4136.104677
2698     16000.0  4131.233333
27       12378.0  4008.620000
73       12435.0  3914.945000

#### Customer Total Purchase Quantity

In [47]:
total = df.groupby("CustomerID")["Quantity"].sum().reset_index()
total

      CustomerID  Quantity
0        12346.0         0
1        12347.0      2458
2        12348.0      2341
3        12349.0       631
4        12350.0       197
...          ...       ...
4367     18280.0        45
4368     18281.0        54
4369     18282.0        98
4370     18283.0      1357
4371     18287.0      1586

[4372 rows x 2 columns]

##### Top 10 (Customer Total Purchase Quantity)

In [48]:
total.sort_values(by="Quantity",ascending=False).head(10)

      CustomerID  Quantity
1703     14646.0    196719
55       12415.0     77242
1895     14911.0     77155
3758     17450.0     69009
4233     18102.0     64122
3801     17511.0     63012
1005     13694.0     61899
1447     14298.0     58021
1345     14156.0     56908
3202     16684.0     49390

#### How many unique products has each customer purchased?

In [54]:
unqi_stock = df.groupby("CustomerID")["StockCode"].nunique().reset_index()
unqi_stock

      CustomerID  StockCode
0        12346.0          1
1        12347.0        103
2        12348.0         22
3        12349.0         73
4        12350.0         17
...          ...        ...
4367     18280.0         10
4368     18281.0          7
4369     18282.0         12
4370     18283.0        263
4371     18287.0         59

[4372 rows x 2 columns]

##### Top 10

In [56]:
unqi_stock.sort_values(by="StockCode",ascending=False).head(10)

      CustomerID  StockCode
1895     14911.0       1794
330      12748.0       1769
4042     17841.0       1331
1300     14096.0       1121
1447     14298.0        884
1674     14606.0        832
1794     14769.0        718
1345     14156.0        716
1703     14646.0        703
568      13089.0        636

#### Customer Purchase Frequency

In [62]:
freq = df.groupby('CustomerID')['InvoiceNo'].nunique().reset_index()
freq[freq["InvoiceNo"] >= 5]

      CustomerID  InvoiceNo
1        12347.0          7
5        12352.0         11
12       12359.0          6
15       12362.0         13
29       12380.0          5
...          ...        ...
4342     18245.0          8
4351     18257.0         12
4353     18260.0          8
4361     18272.0          7
4370     18283.0         16

[1375 rows x 2 columns]

#### Identify the date of the first purchase and the date of the last purchase for each customer.

In [64]:
duration = df.groupby("CustomerID")["InvoiceDate"].agg(First_InvoiceDate="min", Last_InvoiceDate="max").reset_index()
duration

      CustomerID   First_InvoiceDate    Last_InvoiceDate
0        12346.0 2011-01-18 10:01:00 2011-01-18 10:17:00
1        12347.0 2010-12-07 14:57:00 2011-12-07 15:52:00
2        12348.0 2010-12-16 19:09:00 2011-09-25 13:13:00
3        12349.0 2011-11-21 09:51:00 2011-11-21 09:51:00
4        12350.0 2011-02-02 16:01:00 2011-02-02 16:01:00
...          ...                 ...                 ...
4367     18280.0 2011-03-07 09:52:00 2011-03-07 09:52:00
4368     18281.0 2011-06-12 10:53:00 2011-06-12 10:53:00
4369     18282.0 2011-08-05 13:35:00 2011-12-02 11:43:00
4370     18283.0 2011-01-06 14:14:00 2011-12-06 12:02:00
4371     18287.0 2011-05-22 10:39:00 2011-10-28 09:29:00

[4372 rows x 3 columns]

In [73]:
whole_days = (duration["Last_InvoiceDate"] - duration["First_InvoiceDate"]).reset_index()
whole_days

      index                 0
0         0   0 days 00:16:00
1         1 365 days 00:55:00
2         2 282 days 18:04:00
3         3   0 days 00:00:00
4         4   0 days 00:00:00
...     ...               ...
4367   4367   0 days 00:00:00
4368   4368   0 days 00:00:00
4369   4369 118 days 22:08:00
4370   4370 333 days 21:48:00
4371   4371 158 days 22:50:00

[4372 rows x 2 columns]

In [74]:
customer_summary = df.groupby("CustomerID").agg(
    Total_Net_Revenue=("Revenue", "sum"),
    Unique_Invoice_Count=("InvoiceNo", "nunique"), 
    Total_Net_Quantity=("Quantity", "sum"), 
    Unique_StockCode_Count=("StockCode", "nunique"),  
    First_Purchase_Date=("InvoiceDate", "min"),       
    Last_Purchase_Date=("InvoiceDate", "max")         
).reset_index()
customer_summary["Purchase_History_Duration_Days"] = (
    customer_summary["Last_Purchase_Date"] - customer_summary["First_Purchase_Date"]
).dt.days

customer_summary

,CustomerID,Total_Net_Revenue,Unique_Invoice_Count,Total_Net_Quantity,Unique_StockCode_Count,First_Purchase_Date,Last_Purchase_Date,Purchase_History_Duration_Days
0,12346.0,0.00,2,0,1,2011-01-18 10:01:00,2011-01-18 10:17:00,0
1,12347.0,4310.00,7,2458,103,2010-12-07 14:57:00,2011-12-07 15:52:00,365
2,12348.0,1797.24,4,2341,22,2010-12-16 19:09:00,2011-09-25 13:13:00,282
3,12349.0,1757.55,1,631,73,2011-11-21 09:51:00,2011-11-21 09:51:00,0
4,12350.0,334.40,1,197,17,2011-02-02 16:01:00,2011-02-02 16:01:00,0
...,...,...,...,...,...,...,...,...
4367,18280.0,180.60,1,45,10,2011-03-07 09:52:00,2011-03-07 09:52:00,0
4368,18281.0,80.82,1,54,7,2011-06-12 10:53:00,2011-06-12 10:53:00,0
4369,18282.0,176.60,3,98,12,2011-08-05 13:35:00,2011-12-02 11:43:00,118
4370,18283.0,2045.53,16,1357,263,2011-01-06 14:14:00,2011-12-06 12:02:00,333
4371,18287.0,1837.28,3,1586,59,2011-05-22 10:39:00,2011-10-28 09:29:00,158

#### Save File

In [75]:
customer_summary.to_excel("customer_summary.xlsx", index=False)