In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel("online_retail_cleaned.xlsx")

In [2]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

#### Product Revenue Analysis

In [5]:
pra = df.groupby("StockCode")["Revenue"].sum().reset_index()
pra

         StockCode  Revenue
0            10002   759.89
1            10080   119.09
2            10120    40.32
3            10125   993.99
4            10133  1535.40
...            ...      ...
4065  gift_0001_20   167.05
4066  gift_0001_30   175.53
4067  gift_0001_40   100.70
4068  gift_0001_50   167.56
4069             m     2.55

[4070 rows x 2 columns]

###### Top 10

In [7]:
pra.sort_values(by="Revenue",ascending=False).head(10)

     StockCode    Revenue
4059       DOT  206245.48
1271     22423  164459.49
2517     47566   98243.88
3670    85123A   97838.45
3659    85099B   92175.79
1905     23084   66661.63
4062      POST   66230.64
966      22086   63715.24
2735     84879   58792.42
2590     79321   53746.66

#### Product Quantity Analysis

In [10]:
pqa = df.groupby("StockCode")["Quantity"].sum().reset_index()
pqa

         StockCode  Quantity
0            10002      1037
1            10080       495
2            10120       192
3            10125      1295
4            10133      2764
...            ...       ...
4065  gift_0001_20        20
4066  gift_0001_30        37
4067  gift_0001_40         3
4068  gift_0001_50         4
4069             m         1

[4070 rows x 2 columns]

##### PQA TOP 10

In [11]:
pqa.sort_values(by="Quantity",ascending=False).head(10)

     StockCode  Quantity
1070     22197     56427
2622     84077     53751
3659    85099B     47260
3670    85123A     38811
2735     84879     36122
377      21212     36016
1905     23084     30597
1335     22492     26437
1453     22616     26299
889      21977     24719

#### Country Performance

##### Total Net Revenue

In [12]:
ctnr = df.groupby("Country")["Revenue"].sum().reset_index()
ctnr

                 Country      Revenue
0              Australia   137009.770
1                Austria    10154.320
2                Bahrain      548.400
3                Belgium    40910.960
4                 Brazil     1143.600
5                 Canada     3666.380
6        Channel Islands    20076.390
7                 Cyprus    12858.760
8         Czech Republic      707.720
9                Denmark    18768.140
10                  EIRE   262993.380
11    European Community     1291.750
12               Finland    22326.740
13                France   197317.110
14               Germany   221509.470
15                Greece     4710.520
16             Hong Kong     9908.240
17               Iceland     4310.000
18                Israel     7901.970
19                 Italy    16890.510
20                 Japan    35340.620
21               Lebanon     1693.880
22             Lithuania     1661.060
23                 Malta     2505.470
24           Netherlands   284661.540
25                Norway    35163.460
26                Poland     7213.140
27              Portugal    29302.970
28                   RSA     1002.310
29          Saudi Arabia      131.170
30             Singapore     9120.390
31                 Spain    54756.030
32                Sweden    36585.410
33           Switzerland    56363.050
34                   USA     1730.920
35  United Arab Emirates     1902.280
36        United Kingdom  8167128.184
37           Unspecified     4740.940

##### Country Unique Invoices

In [13]:
cui = df.groupby("Country")["InvoiceNo"].nunique().reset_index()
cui

                 Country  InvoiceNo
0              Australia         69
1                Austria         19
2                Bahrain          4
3                Belgium        119
4                 Brazil          1
5                 Canada          6
6        Channel Islands         33
7                 Cyprus         20
8         Czech Republic          5
9                Denmark         21
10                  EIRE        360
11    European Community          5
12               Finland         48
13                France        461
14               Germany        603
15                Greece          6
16             Hong Kong         15
17               Iceland          7
18                Israel          9
19                 Italy         55
20                 Japan         28
21               Lebanon          1
22             Lithuania          4
23                 Malta         10
24           Netherlands        101
25                Norway         40
26                Poland         24
27              Portugal         71
28                   RSA          1
29          Saudi Arabia          2
30             Singapore         10
31                 Spain        105
32                Sweden         46
33           Switzerland         74
34                   USA          7
35  United Arab Emirates          3
36        United Kingdom      23494
37           Unspecified         13

##### Country Unique Customer

In [14]:
cuc = df.groupby("Country")["CustomerID"].nunique().reset_index()
cuc

                 Country  CustomerID
0              Australia           9
1                Austria          11
2                Bahrain           2
3                Belgium          25
4                 Brazil           1
5                 Canada           4
6        Channel Islands           9
7                 Cyprus           8
8         Czech Republic           1
9                Denmark           9
10                  EIRE           3
11    European Community           1
12               Finland          12
13                France          87
14               Germany          95
15                Greece           4
16             Hong Kong           0
17               Iceland           1
18                Israel           4
19                 Italy          15
20                 Japan           8
21               Lebanon           1
22             Lithuania           1
23                 Malta           2
24           Netherlands           9
25                Norway          10
26                Poland           6
27              Portugal          19
28                   RSA           1
29          Saudi Arabia           1
30             Singapore           1
31                 Spain          31
32                Sweden           8
33           Switzerland          21
34                   USA           4
35  United Arab Emirates           2
36        United Kingdom        3950
37           Unspecified           4

In [15]:
country_summary = df.groupby("Country").agg(
    Total_Net_Revenue=("Revenue","sum"),
    Unique_Invoices=("InvoiceNo","nunique"),
    Unique_Customers=("CustomerID","nunique")).reset_index()
country_summary

                 Country  Total_Net_Revenue  Unique_Invoices  Unique_Customers
0              Australia         137009.770               69                 9
1                Austria          10154.320               19                11
2                Bahrain            548.400                4                 2
3                Belgium          40910.960              119                25
4                 Brazil           1143.600                1                 1
5                 Canada           3666.380                6                 4
6        Channel Islands          20076.390               33                 9
7                 Cyprus          12858.760               20                 8
8         Czech Republic            707.720                5                 1
9                Denmark          18768.140               21                 9
10                  EIRE         262993.380              360                 3
11    European Community           1291.750                5                 1
12               Finland          22326.740               48                12
13                France         197317.110              461                87
14               Germany         221509.470              603                95
15                Greece           4710.520                6                 4
16             Hong Kong           9908.240               15                 0
17               Iceland           4310.000                7                 1
18                Israel           7901.970                9                 4
19                 Italy          16890.510               55                15
20                 Japan          35340.620               28                 8
21               Lebanon           1693.880                1                 1
22             Lithuania           1661.060                4                 1
23                 Malta           2505.470               10                 2
24           Netherlands         284661.540              101                 9
25                Norway          35163.460               40                10
26                Poland           7213.140               24                 6
27              Portugal          29302.970               71                19
28                   RSA           1002.310                1                 1
29          Saudi Arabia            131.170                2                 1
30             Singapore           9120.390               10                 1
31                 Spain          54756.030              105                31
32                Sweden          36585.410               46                 8
33           Switzerland          56363.050               74                21
34                   USA           1730.920                7                 4
35  United Arab Emirates           1902.280                3                 2
36        United Kingdom        8167128.184            23494              3950
37           Unspecified           4740.940               13                 4

##### TOP 10 COUNTRY

In [17]:
country_summary.sort_values(by="Total_Net_Revenue",ascending=False).head(10)

           Country  Total_Net_Revenue  Unique_Invoices  Unique_Customers
36  United Kingdom        8167128.184            23494              3950
24     Netherlands         284661.540              101                 9
10            EIRE         262993.380              360                 3
14         Germany         221509.470              603                95
13          France         197317.110              461                87
0        Australia         137009.770               69                 9
33     Switzerland          56363.050               74                21
31           Spain          54756.030              105                31
3          Belgium          40910.960              119                25
32          Sweden          36585.410               46                 8

## Business Insights

1. **United Kingdom dominates revenue:** The United Kingdom generated the highest total net revenue of approximately **8.17 million**, making it the company's largest market by a significant margin.

2. **Strong customer and invoice base in the UK:** The United Kingdom recorded **23,494 unique invoices** and **3,950 unique customers**, considerably more than any other country in the dataset. This indicates that the business relies heavily on the UK market.

3. **The Netherlands is the second-largest market:** The Netherlands generated approximately **284,661.54** in net revenue, followed by EIRE at **262,993.38** and Germany at **221,509.47**. These countries represent important markets outside the UK.

4. **Revenue is concentrated in a few countries:** The difference between the UK's revenue and that of the other countries is substantial. This suggests a strong dependence on the UK market and highlights an opportunity to grow sales in other countries.

5. **Product performance should be evaluated using multiple metrics:** Products with the highest net revenue may not always have the highest net quantity. Comparing both metrics helps distinguish high-revenue products from products sold in larger quantities.

6. **Special product codes require further investigation:** The code `DOT` ranked first in the product revenue analysis. Its meaning should be verified before treating it as a regular product, since special codes may represent services or other charges.