In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel("online_retail_cleaned.xlsx")

In [2]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

## Monthly Revenue Trend

In [11]:
df_monthly = df.groupby(df["InvoiceDate"].dt.to_period("M"))["Revenue"].sum().reset_index()
df_monthly

   InvoiceDate      Revenue
0      2010-12   746723.610
1      2011-01   558448.560
2      2011-02   497026.410
3      2011-03   682013.980
4      2011-04   492367.841
5      2011-05   722094.100
6      2011-06   689977.230
7      2011-07   680156.991
8      2011-08   681386.460
9      2011-09  1017596.682
10     2011-10  1069368.230
11     2011-11  1456145.800
12     2011-12   432701.060

#### Sort Revenue in descending order

In [14]:
descending_order = df_monthly.sort_values(by="Revenue",ascending=False)
descending_order

   InvoiceDate      Revenue
11     2011-11  1456145.800
10     2011-10  1069368.230
9      2011-09  1017596.682
0      2010-12   746723.610
5      2011-05   722094.100
6      2011-06   689977.230
3      2011-03   682013.980
8      2011-08   681386.460
7      2011-07   680156.991
1      2011-01   558448.560
2      2011-02   497026.410
4      2011-04   492367.841
12     2011-12   432701.060

##### Top 5

In [15]:
descending_order.head(5)

   InvoiceDate      Revenue
11     2011-11  1456145.800
10     2011-10  1069368.230
9      2011-09  1017596.682
0      2010-12   746723.610
5      2011-05   722094.100

##### Last 5

In [16]:
descending_order.tail(5)

   InvoiceDate     Revenue
7      2011-07  680156.991
1      2011-01  558448.560
2      2011-02  497026.410
4      2011-04  492367.841
12     2011-12  432701.060

### Monthly Revenue Trend — Business Insights

1. **November 2011 was the strongest month:** It generated the highest net revenue of approximately 1.46 million, indicating a peak in business activity during this period.

2. **Strong performance in September and October:** Both months recorded revenue above 1 million, suggesting increased sales activity leading into November.

3. **April 2011 was the weakest full month in the reported results:** Revenue was approximately 492,367.84, making it the lowest among the listed months.

4. **December 2011 requires careful interpretation:** Its reported revenue was lower than most other months, but the dataset ends on 9 December 2011. Therefore, it should not be compared directly with complete months.

5. **Business planning opportunity:** The business can investigate the factors behind the September–November revenue peak and use these patterns to support inventory and sales planning.

## Monthly Invoice Activity

In [20]:
df_invoice = df.groupby(df["InvoiceDate"].dt.to_period("M"))["InvoiceNo"].nunique().reset_index()
df_invoice

   InvoiceDate  InvoiceNo
0      2010-12       2025
1      2011-01       1476
2      2011-02       1393
3      2011-03       1983
4      2011-04       1744
5      2011-05       2162
6      2011-06       2012
7      2011-07       1927
8      2011-08       1737
9      2011-09       2327
10     2011-10       2637
11     2011-11       3462
12     2011-12       1015

In [21]:
inv_descending_order = df_invoice.sort_values(by="InvoiceNo",ascending=False)
inv_descending_order

   InvoiceDate  InvoiceNo
11     2011-11       3462
10     2011-10       2637
9      2011-09       2327
5      2011-05       2162
0      2010-12       2025
6      2011-06       2012
3      2011-03       1983
7      2011-07       1927
4      2011-04       1744
8      2011-08       1737
1      2011-01       1476
2      2011-02       1393
12     2011-12       1015

#### Top 5

In [22]:
inv_descending_order.head(5)

   InvoiceDate  InvoiceNo
11     2011-11       3462
10     2011-10       2637
9      2011-09       2327
5      2011-05       2162
0      2010-12       2025

#### Last 5

In [23]:
inv_descending_order.tail(5)

   InvoiceDate  InvoiceNo
4      2011-04       1744
8      2011-08       1737
1      2011-01       1476
2      2011-02       1393
12     2011-12       1015

### Monthly Invoice Activity — Business Insights

1. **November 2011 had the highest invoice activity:** The month recorded 3,462 unique invoices, indicating the strongest ordering activity in the observed period.

2. **September to November showed strong activity:** Invoice counts increased from 2,327 in September to 2,637 in October and 3,462 in November. This pattern aligns with the high revenue recorded during these months.

3. **January and February had lower invoice counts:** These months recorded 1,476 and 1,393 unique invoices respectively, indicating lower ordering activity than most of the stronger months in the dataset.

4. **December 2011 is an incomplete period:** Only data through 9 December is available, so its 1,015 invoices should not be interpreted as a full-month result.

5. **Business planning opportunity:** The business can investigate why ordering activity rises toward November and prepare inventory and operational capacity for similar peak periods.

## Day-of-Week Analysis

In [30]:
df_daysofweek_revenue = df.groupby(df["InvoiceDate"].dt.day_name())["Revenue"].sum().reset_index()
df_daysofweek_revenue

  InvoiceDate      Revenue
0      Friday  1537958.621
1      Monday  1584895.301
2      Sunday   798659.461
3    Thursday  2108701.530
4     Tuesday  1965703.611
5   Wednesday  1730088.430

In [31]:
df_daysofweek_invoice = df.groupby(df["InvoiceDate"].dt.day_name())["InvoiceNo"].nunique().reset_index()
df_daysofweek_invoice

  InvoiceDate  InvoiceNo
0      Friday       4184
1      Monday       4138
2      Sunday       2381
3    Thursday       5660
4     Tuesday       4722
5   Wednesday       4815

### Day-of-Week Analysis — Business Insights

1. **Thursday was the strongest day:** It generated the highest net revenue of approximately 2.11 million and recorded 5,660 unique invoices, indicating the highest observed business activity.

2. **Tuesday also performed strongly:** It generated approximately 1.97 million in net revenue, making it the second-highest revenue day.

3. **Sunday had the lowest activity:** Sunday recorded approximately 798,659.46 in net revenue and 2,381 unique invoices, the lowest figures among the reported weekdays.

4. **Revenue and invoice activity followed a similar pattern:** Thursday ranked highest and Sunday ranked lowest for both metrics. This suggests that differences in invoice volume may contribute to differences in daily revenue.

5. **Operational planning opportunity:** The business can investigate the reasons for stronger Thursday activity and consider aligning inventory and staffing with observed demand patterns. Sunday’s lower activity should be interpreted cautiously without confirmed business operating hours.

# Notebook 07 — Time Analysis

## Project Objective

The objective of this analysis was to understand how revenue and invoice activity vary over time, identify peak and slower periods, and extract useful business insights for planning.

## Key Findings

### 1. Monthly Revenue Trend
- November 2011 recorded the highest monthly net revenue at approximately **1.46 million**.
- October and September 2011 were also strong months, with revenue exceeding 1 million in each month.
- April 2011 recorded the lowest revenue among the complete months analyzed, at approximately **492,367.84**.
- December 2011 is an incomplete month in the dataset, which ends on 9 December 2011.

### 2. Monthly Invoice Activity
- November 2011 recorded the highest invoice activity, with **3,462 unique invoices**.
- Invoice activity increased from September through November 2011, following a pattern similar to monthly revenue.
- January and February 2011 had relatively low invoice counts compared with the peak months.
- December 2011 recorded 1,015 unique invoices, but this represents only a partial month.

### 3. Day-of-Week Analysis
- **Thursday** was the strongest observed day, generating approximately **2.11 million** in net revenue and recording **5,660 unique invoices**.
- Tuesday ranked second in revenue, at approximately **1.97 million**.
- **Sunday** had the lowest observed revenue, at approximately **798,659.46**, and the fewest unique invoices, at **2,381**.
- Revenue and invoice activity followed similar weekday patterns, with Thursday highest and Sunday lowest.

## Overall Business Insights

1. **Seasonal planning:** The strong performance observed from September to November suggests that the business should investigate potential seasonal demand and prepare inventory and operational capacity accordingly.

2. **Weekly demand patterns:** Thursday had the highest revenue and invoice activity. This pattern can help inform staffing and inventory planning, subject to confirmation of operating schedules.

3. **Revenue and invoice activity:** Months and weekdays with more invoices generally showed stronger total revenue in the observed results. However, invoice volume alone does not explain all revenue differences.

4. **Data completeness matters:** December 2011 contains data only through 9 December. Comparisons involving this month should account for its shorter observation period.

## Conclusion

The time analysis identified November 2011 as the peak month for both net revenue and invoice activity, while Thursday was the strongest weekday in the observed data. These findings can support preliminary sales, inventory, and staffing decisions. Further investigation would be needed to establish the causes of these patterns and determine whether they recur consistently.

**Tools used:** Python, Pandas, `groupby()`, `agg()`, `sum()`, `nunique()`, `dt.to_period()`, `dt.day_name()`, and `sort_values()`.